# Test various C programs written with the help of: https://metacpan.org/pod/Preprocess::Ops

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential gdb tree gtk+-3.0-dev
        sudo cpan install Data::Table::Text Data::Dump Dita::PCD Getopt::Long File::Basename Java::Doc Preprocess::Ops

    - name: Install Valgrind
      run: |
        sudo apt -y install valgrind

    - name: Home
      run: |
        echo $HOME
        tree

    - name: Run arenaRedBlackTree
      if: always()
      run: |
        (cd c/z/arenaRedBlackTree/; perl perl/makeWithPerl/makeWithPerl.pl --c --run arenaRedBlackTree.c --cIncludes c/includes)
        (cd c/z/arenaRedBlackTree/; perl perl/makeWithPerl/makeWithPerl.pl --c --run arenaRedBlackTree.c --cIncludes c/includes --valgrind)

    - name: Run arenaTree
      if: always()
      run: |
        (cd c/z/arenaTree/; perl perl/makeWithPerl/makeWithPerl.pl --c --run arenaTree.c --cIncludes c/includes)
        (cd c/z/arenaTree/; perl perl/makeWithPerl/makeWithPerl.pl --c --run arenaTree.c --cIncludes c/includes --valgrind)

    - name: Run stringBuffer
      if: always()
      run: |
        (cd c/z/stringBuffer/; perl perl/makeWithPerl/makeWithPerl.pl --c --run stringBuffer.c --cIncludes c/includes)
        (cd c/z/stringBuffer/; perl perl/makeWithPerl/makeWithPerl.pl --c --run stringBuffer.c --cIncludes c/includes --valgrind)

    - name: Run xml
      if: always()
      run: |
        (cd c/z/xml/; perl perl/makeWithPerl/makeWithPerl.pl --c --run xml.c --cIncludes c/includes)
        (cd c/z/xml/; perl perl/makeWithPerl/makeWithPerl.pl --c --run xml.c --cIncludes c/includes --valgrind)

    - name: Run utilities
      if: always()
      run: |
        (cd c/z/utilities/; perl perl/makeWithPerl/makeWithPerl.pl --c --run utilities.c --cIncludes c/includes)
        (cd c/z/utilities/; perl perl/makeWithPerl/makeWithPerl.pl --c --run utilities.c --cIncludes c/includes --valgrind)

    - name: Run pangoText
      if: always()
      run: |
        (cd c/g/pangoText/; perl perl/makeWithPerl/makeWithPerl.pl --c --run pangoText.c --cIncludes c/includes)
        (cd c/g/pangoText/; perl perl/makeWithPerl/makeWithPerl.pl --c --run pangoText.c --cIncludes c/includes --valgrind)

