# Test various C programs written with the help of: https://metacpan.org/pod/Preprocess::Ops

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential gdb tree
        sudo cpan install Data::Table::Text Data::Dump Dita::PCD Getopt::Long File::Basename Java::Doc Preprocess::Ops

    - name: Install Valgrind
      run: |
        sudo apt -y install valgrind

    - name: Home
      run: |
        echo $HOME
        tree

    - name: Run arenaRedBlackTree
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/arenaRedBlackTree/arenaRedBlackTree.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/arenaRedBlackTree/arenaRedBlackTree.c --cIncludes c/includes --valgrind

    - name: Run arenaTree
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/arenaTree/arenaTree.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/arenaTree/arenaTree.c --cIncludes c/includes --valgrind

    - name: Run fileName
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/fileName/fileName.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/fileName/fileName.c --cIncludes c/includes --valgrind

    - name: Run readOnlyBytes
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/readOnlyBytes/readOnlyBytes.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/readOnlyBytes/readOnlyBytes.c --cIncludes c/includes --valgrind

    - name: Run stringBuffer
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/stringBuffer/stringBuffer.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/stringBuffer/stringBuffer.c --cIncludes c/includes --valgrind

    - name: Run xml
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/xml/xml.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/xml/xml.c --cIncludes c/includes --valgrind

    - name: Run utilities
      if: always()
      run: |
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/utilities/utilities.c --cIncludes c/includes
        perl perl/makeWithPerl/makeWithPerl.pl --c --run c/z/utilities/utilities.c --cIncludes c/includes --valgrind

