# Test various C programs written with the help of: https://metacpan.org/pod/Preprocess::Ops

name: Test

on:
  push

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Env
      run: |
        echo $HOME
        pwd
        ls -la fonts/NotoSansMono-Regular.ttf
        md5dum fonts/NotoSansMono-Regular.ttf

    - name: Install
      run: |
        sudo apt update
        sudo apt -y install build-essential gdb tree gtk+-3.0-dev
        sudo cpan install Data::Table::Text Data::Dump Dita::PCD Getopt::Long File::Basename Java::Doc Preprocess::Ops

    - name: Install Valgrind
      run: |
        sudo apt -y install valgrind

    - name: Home
      run: |
        tree

    - name: Run arenaList
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/z/arenaList/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/arenaList//arenaList.c --cIncludes /home/runner/work/C/C/c/includes)
        (cd /home/runner/work/C/C/c/z/arenaList/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/arenaList//arenaList.c --cIncludes /home/runner/work/C/C/c/includes --valgrind)

    - name: Run arenaTree
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/z/arenaTree/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/arenaTree//arenaTree.c --cIncludes /home/runner/work/C/C/c/includes)
        (cd /home/runner/work/C/C/c/z/arenaTree/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/arenaTree//arenaTree.c --cIncludes /home/runner/work/C/C/c/includes --valgrind)

    - name: Run stringBuffer
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/z/stringBuffer/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/stringBuffer//stringBuffer.c --cIncludes /home/runner/work/C/C/c/includes)
        (cd /home/runner/work/C/C/c/z/stringBuffer/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/stringBuffer//stringBuffer.c --cIncludes /home/runner/work/C/C/c/includes --valgrind)

    - name: Run xml
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/z/xml/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/xml//xml.c --cIncludes /home/runner/work/C/C/c/includes)
        (cd /home/runner/work/C/C/c/z/xml/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/xml//xml.c --cIncludes /home/runner/work/C/C/c/includes --valgrind)

    - name: Run utilities
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/z/utilities/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/utilities//utilities.c --cIncludes /home/runner/work/C/C/c/includes)
        (cd /home/runner/work/C/C/c/z/utilities/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/z/utilities//utilities.c --cIncludes /home/runner/work/C/C/c/includes --valgrind)

    - name: Run cairoText
      if: always()
      run: |
        (cd /home/runner/work/C/C/c/g/cairoText/; perl /home/runner/work/C/C/perl/makeWithPerl/makeWithPerl.pl --c --run /home/runner/work/C/C/c/g/cairoText//cairoText.c --cIncludes /home/runner/work/C/C/c/includes)

